# Generated by Django 5.0 on 2024-05-07 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reading_persona', models.TextField(blank=True, help_text="User's reading persona")),
                ('vote_count', models.IntegerField(blank=True, default=0, help_text="Count user's votes, reset every 20 books.", null=True)),
                ('favorite_books', models.ManyToManyField(blank=True, help_text="User's favorite books", related_name='favorited_by', to='projects.books')),
                ('read_books', models.ManyToManyField(blank=True, help_text="User's read books", related_name='read_by', to='projects.books')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
