# Generated by Django 5.0 on 2024-03-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_books', models.TextField(blank=True, help_text="List of user's favorite books")),
                ('user_reading_persona', models.TextField(blank=True, help_text="User's reading persona")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
