# Generated by Django 5.0 on 2024-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookdata',
            name='last_recommendation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
