# Generated by Django 5.0 on 2024-03-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookdata',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, help_text="Count user's votes, reset every 20 books.", null=True),
        ),
    ]
