# Generated by Django 5.0 on 2024-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_books_amazon_id'),
        ('users', '0002_userbookdata_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookdata',
            name='read_books',
            field=models.ManyToManyField(blank=True, help_text="User's read books", related_name='read_by', to='projects.books'),
        ),
        migrations.RemoveField(
            model_name='userbookdata',
            name='favorite_books',
        ),
        migrations.AddField(
            model_name='userbookdata',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, help_text="User's favorite books", related_name='favorited_by', to='projects.books'),
        ),
    ]
