# Generated by Django 5.0 on 2024-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='categories',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('name', 'author')},
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
