# Generated by Django 5.0 on 2024-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='upvotes_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
