# Generated by Django 5.0 on 2024-06-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_books_categories_alter_books_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='recommended_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
