# Generated by Django 5.0 on 2023-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
