# Generated by Django 5.0 on 2024-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_books_upvotes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
