# Generated by Django 5.0 on 2023-12-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='featured_image',
            field=models.ImageField(blank=True, default='book.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
