# Generated by Django 5.0 on 2024-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_books_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='published_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
