# Generated by Django 5.0 on 2024-03-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_books_published_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('name', 'author')},
        ),
    ]
