# Generated by Django 5.0 on 2024-03-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_books_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='amazon_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
